<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Blog
                </h1>

                <!-- First Blog Post -->

                <?php foreach($article->getAll() as $row):?>

                <h2>
                    <a href="#"><?=ucfirst($row["title"])?></a>
                </h2>
                <p class="lead">
                    by <a href="index.php"><?=$row["pseudo"]?></a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <?=$row["date"]?></p>
                <p>
                    <?php foreach($article->showTag($row["id"]) as $row2):?>
                    <a href="tags.php?tag=">
                        <span class="btn btn-default btn-xs"><span class="glyphicon glyphicon-tag">
                        </span>&nbsp;<?=$row2["name"]?></span>
                    </a>
                    <?php endforeach;?>
                    
                    <?php var_dump($article->showTag($row["id"])); ?>
                </p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p><?=$row["description"]?></p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

                <?php endforeach;?>


                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">                   
                    <div class="input-group">
                    <?php echo $userManager->isLogged();?>
                    </div>
                    <!-- /.input-group -->
                </div>


                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Tags</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>
